FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy project
COPY . .

EXPOSE 3000

# Development command
CMD ["npm", "run", "dev"]
