# Generated by Django 5.2.9 on 2026-01-06 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_custom_domain_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='property',
            name='primary_color',
            field=models.CharField(blank=True, default='#6366f1', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.accommodation', verbose_name='Acomodação')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
