# Generated by Django 5.2.9 on 2026-01-06 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_logo_property_primary_color_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('MANAGER', 'Gerente')], default='MANAGER', max_length=20, verbose_name='Papel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='properties.property', verbose_name='Propriedade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso à Propriedade',
                'verbose_name_plural': 'Acessos às Propriedades',
                'db_table': 'property_accesses',
                'indexes': [models.Index(fields=['user', 'property'], name='property_ac_user_id_fe7846_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
