# Generated by Django 5.2.9 on 2026-01-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_populate_property_access'),
    ]

    operations = [
    ]
