# Generated by Django 5.2.9 on 2026-01-01 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_documento_property_dominio_personalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Básico, Pro, Enterprise', max_length=100)),
                ('gateway_code', models.CharField(blank=True, help_text='ID do plano no Stripe/Gateway', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('trialing', 'Período de Teste'), ('past_due', 'Pagamento Pendente'), ('canceled', 'Cancelada'), ('unpaid', 'Inadimplente')], default='trialing', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='ID da assinatura no Gateway', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='properties.property', verbose_name='Pousada')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Pagamento')),
                ('gateway_status', models.CharField(choices=[('succeeded', 'Sucesso'), ('pending', 'Pendente'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transação Gateway')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
