# Generated by Django 5.2.9 on 2026-01-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='dominio_personalizado',
            field=models.CharField(blank=True, help_text='Domínio próprio da pousada (ex: pousadavistadaserra.com.br)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='E-mail principal de contato', max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Ex: 08:00 - 22:00', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='link_google_maps',
            field=models.URLField(blank=True, help_text='Link do Google Maps'),
        ),
        migrations.AddField(
            model_name='property',
            name='link_rede_social',
            field=models.URLField(blank=True, help_text='Link do Instagram, Facebook, etc.'),
        ),
        migrations.AddField(
            model_name='property',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Telefone/WhatsApp principal', max_length=20),
        ),
    ]
